# 第7章 异常处理

##   异常

1. 异常的体系结构

```
java.lang.Throwable
    |---java.lang.Error:一般不编写针对性的代码进行处理
    |---java.lang.Exception:可以进行异常的处理
           |---编译时异常checked
                |---IOException
                    |---FileNotFoundException
                |---ClassNotFoundException
           |---运行时异常unchecked
                |---NullPointerException
                |---ArrayIndexOutOfBoundsException
                |---ClassCastException
                |---NumberFormatException
                |---InputMismatchException
                |---ArithmeticException
```

2. 从程序的执行过程，看编译时异常和运行时异常
   编译时异常：执行javac.exe命令时，可能出现的异常
   运行时异常：执行java.exe命令时，可能出现的异常

3. 常见的异常类型，请举例说明

   ```java
   public class ExceptionTest {
       //*************************以下是编译时异常********************************
   //    @Test
   //    public void test7(){
   //        File file = new File("hello.txt");
   //        FileInputStream fis = new FileInputStream(file);
   //
   //        int data = fis.read();
   //        while(data != -1){
   //            System.out.print((char)data);
   //            data = fis.read();
   //        }
   //        fis.close();
   //    }
   
   
   
       //*************************以下是运行时异常********************************
       //NullPointerException
   //    @Test
   //    public void test1(){
   //        int[] arr = null;
   //        System.out.println(arr[3]);
   
   //        String str = null;
   //        System.out.println(str.charAt(0));
   //    }
   
       //ArrayIndexOutOfBoundsException
   //    public void test2(){
   //        int[] arr = new int[10];
   //            System.out.println(arr[10]);
   //    }
   
       //ClassCastException
   //    public void test3(){
   //        Object obj = new Date();
   //        String str = (String)obj;
   //    }
   
       //NumberFormatException
   //    public void test4(){
   //        String str = "123";
   //        int num = Integer.parseInt(str);
   //    }
   
       //InputMismatchException
   //    public void test4(){
   //        Scanner scanner = new Scanner(System.in);
   //        int score = scanner.nextInt();
   //        System.out.println(score);
   //    }
   
       //ArithmeticException
   //    public void test5(){
   //        int a = 10;
   //        int b = 0;
   //        System.out.println(a / b);
   //    }
   
   }
   ```

## 异常的处理

1. java异常处理的抓抛模型

   ```
   过程一：“抛”：程序在正常执行的过程中，一旦出现异常，就会在异常代码处生成一个异常对应类的对象
               并将此对象抛出
               一旦抛出对象以后，其后的代码就不再执行
   
               关于异常对象的产生：1. 系统自动生成的异常对象
                               2. 手动的生成一个异常的对象，并抛出（throw）
   
   过程二：“抓”：可以理解为异常处理的方式：1. try-catch-finally 2. throws
   ```

2. 异常处理方式一：

   2.1 try-catch-finally的使用：

   ```
       try{
       //可能出现异常的代码
       }catch(异常类型1 变量名1){
       //处理异常的方式1
       }catch(异常类型2 变量名2){
       //处理异常的方式2
       }catch(异常类型3 变量名3){
       //处理异常的方式3
       }catch(异常类型4 变量名4){
       //处理异常的方式4
       }...
       finally{
       //一定会执行的代码
       }
   
   说明：
   1. finally是可选的
   2. 使用try将可能出现异常的代码包装起来，在执行过程中，一旦出现异常，就会生成一个异常类对应的对象
       根据此对象的类型，去catch中匹配
   3. 一旦try中的异常对象匹配到某一个catch，就进入catch中进行异常的处理，一旦处理完成，
       就跳出当前的try-catch结构（在没有写finally的情况下），继续执行其后的代码
   4. catch中的异常类型如果没有子父类关系，则谁声明在上面无所谓
      catch中的异常类型如果满足子父类关系，则子类一定要声明在父类的上面，否则，报错
   5. 常用的异常对象的处理方式：1.String getMessage（）  2.printStackTrace（）
   6. 在try结构中声明的变量，在出了try结构后就不能被调用
   7. try-catch-finally可以嵌套
   
   总结：如何看待代码中的编译时异常和运行时异常？
   体会1：使用try-catch-finally处理编译时异常时，是将程序在编译时就不再报错，但是运行时可能报错
       相当于使用try-catch-finally将一个编译时可能出现的异常，延迟到运行时出现
   
   体会2：开发中由于运行时异常比较常见，我们就不针对运行时异常编写try-catch-finally
       针对编译时异常，我们说一定要考虑异常的处理
   ```

   2.2 finally的使用

   ```
   1. finally是可选的
   
   2. finally中声明的是一定会被执行的代码，即使出现catch中又出现异常了，try中又return语句
       catch中有return的情况
   
   3. 像数据库连接、输入输出流、网络编程中的socket资源，JVM是不能自动的回收的，我们需要手动的进行资源的释放
       此时的资源释放，就需要声明在finally中
   ```

   2.3 面试题

   final、finally、finalize三者的区别？

   类似：
   throw和throws
   Collection和Collections
   String、StringBuffer、StringBuilder
   ArrayList、LinkedList
   HashMap、LinkedHashMap
   重载、重写

   结构不相似的：
   抽象类、接口
   ==、equals()
   sleep()、wait()

3. 异常处理方式二：throws + 异常类型

```
1. "throws + 异常的类型 " 声明在方法的声明处。指明此方法执行时，可能会抛出的异常类型
    一旦方法体执行时，出现异常，仍会在异常代码处生成一个异常类的对象
    此对象满足throws后异常类型时，就会被抛出。异常代码后面的代码就不再执行

2. 体会：try-catch-finally：真正的将异常给处理掉了
        throws的方式只是将异常抛给方法的调用者，并没有真正的将异常处理掉

3. 开发中如何选择try-catch-finally还是throws？
    3.1 如果父类中被重写的方法没有throws方式处理异常，则子类重写的方法也不能使用throws
        意味着如果子类重写的方法中有异常，必须使用try-catch-finally方式处理
    3.2 执行的方法a中先后又调用了另外的几个方法，这几个方法又是递进关系，我们建议这几个方法使用throws
        的方式处理，而执行的方法a可以考虑使用try-catch-finally的方式处理
```

## 手动的抛出异常对象

1. 使用说明
   在程序执行过程中，除了自动抛出异常对象的情况之外，我们还可以手动的throw一个异常类的对象。

2. 面试题
   throw表示抛出一个异常类的对象，生成异常对象的过程。声明在方法体内。
   throws表示异常处理的一种方式，声明在方法的声明处。

3. 典型例题

   ```java
   class Student{
       private int id;
       public void regist(int id) throws Exception {
           if(id > 0){
               this.id = id;
           }else{
   //            System.out.println("输入非法");
               //手动的抛出一个异常对象
   //            throw new RuntimeException("你输入的数据非法");
   //            throw new Exception("你输入的数据非法");
               throw new MyException("不能输入负数");
   
               //错误的：
   //            throw new String("不能输入负数");
           }
       }
   
       @Override
       public String toString() {
           return "Student{" +
                   "id=" + id +
                   '}';
       }
   }
   ```

## 自定义异常类

```java
1. 继承于现有的异常结构：RuntimeException、Exception

2. 提供全局常量：serialVersionUID

3. 提供重载的构造器

public class MyException extends RuntimeException{

    static final long serialVersionUID = -7034897190745766931L;

    public MyException(){

    }

    public MyException(String msg){
        super(msg);
    }
    
}
```

